# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ES <- function(stat, geneOrd, Pmiss, Nr, gs) {
    .Call('gseak_ES', PACKAGE = 'gseak', stat, geneOrd, Pmiss, Nr, gs)
}

ginGS <- function(g, gs, stat) {
    .Call('gseak_ginGS', PACKAGE = 'gseak', g, gs, stat)
}

permutation <- function(x, n) {
    .Call('gseak_permutation', PACKAGE = 'gseak', x, n)
}

